blueprint:
  name: Управление ночником и чайником по будильнику
  description: |
    ### Будильник с управлением устройствами.
    <small>Версия 2026.06.01 Сборка 2</small> 

    <small><a href="https://github.com/S0ft0r/ha-blueprints/blob/main/as-is.md">Отказ от ответственности</a></small>
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/other/dev/dev.alarm.yaml
  author: Softor

  # TODO:
  # - Определять рассвет - включать ли свет после рассвета.
  # - Поднимать жалюзи в спальне
  # - Включать дополнительную технику (ТВ, радио и т.д.)

  input: 
    set_time_alarm:
      name: Будильник
      description: Установка будильника
      selector:
        time: {}

    alarm_section:
      name: Настройка работы будильника
      input:
        alarm_on_days:
          name: Включение будильника
          description: |
            Выбор дней для включения будильника
          default: []
          selector:
            select:
              options:
                - label: Понедельник
                  value: mon
                - label: Вторник
                  value: tue
                - label: Среда
                  value: wed
                - label: Четверг
                  value: thu
                - label: Пятница
                  value: fri
                - label: Суббота
                  value: sat
                - label: Воскресенье
                  value: sun
              sort: false
              multiple: true
              custom_value: false
              mode: list

        alarm_on_options:
          name: Настройки включения устройств 
          selector:
            select:
              options:
                - label: Включение чайника
                  value: on_kettle
                - label: Включение ночника
                  value: on_light
                - label: Проговаривание фразы
                  value: on_phrase
                - label: Включение музыки
                  value: on_music
              sort: false
              multiple: true
              custom_value: false
              mode: list

    kettle_section:
      name: Настройка чайника
      input:
        kettle_switch:
          name: Чайник
          description: |
            Чайник
          default: []
          selector:
            entity:
              filter:
                - domain:
                    - water_heater
              multiple: false
        
        set_kettle_before_alarm:
          name: Включать чайник до будильника за 
          description: ""
          default: "00:10:00"
          selector:
            time: {}

        set_temperature_boil:
          name: Температура кипячения
          description: Температура, ниже которой включается режим кипячения
          default: 40
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "°C"

        set_temperature_heat:
          name: Температура подогрева
          default: 80
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "°C"

    light_section:
      name: Настройка ночника
      input:
        light_switch:
          name: Ночник
          description: ""
          default: []
          selector:
            entity:
              filter:
                - domain:
                    - light
              multiple: true

        set_light_before_alarm:
          name: Включать ночник до будильника за
          description: ""
          default: "00:00:00"
          selector:
            time: {}

        set_sunset:
          name: Включать после рассвета?
          default: false
          selector:
            boolean:

        sun_sensor:
          name: Датчик солнца
          default: sun.sun
          selector:
            entity:
              filter:
                - domain:
                    - sun
              multiple: false
          

    media_section:
      name: Настройка медиаплейера
      description: Алиса
      input:
        media_player:
          name: Медиаплейер
          default: []
          selector:
            entity:
              filter:
                - domain:
                    - media_player
              multiple: false

        set_phrase:
          name: Фраза 
          default: "Вставай, соня. Пора творить!"
          selector:
            text: 

        set_command_base:
          name: Фраза-обращение к колонке.
          default: "Алиса, включи"
          selector:
            text:

        set_command_music:
          name: Текстовая фраза для включения музыки
          description: |
            Фраза будет добавлена после обращения*
            Можно использовать несколько фраз, перечисленных через точку с запятой. 
          default: "пение птиц; шум моря"
          selector:
            text: 
        
        set_random_command:
          name: Случайный выбор фраз
          default: true
          selector:
            boolean:

        set_music_before_alarm:
          name: Включать музыку до будильника за
          description: ""
          default: "00:00:00"
          selector:
            time: {}

    person_section:
      name: Настройка персоны
      input:
        person_home:
          name: Учитывать положение персоны
          default: false
          selector:
            boolean:

        person_sensor:
          name: Персона
          default: []
          selector:
            entity:
              filter:
                - domain:
                    - person
              multiple: true

trigger_variables:
  set_time_alarm: !input set_time_alarm
  kettle_switch: !input kettle_switch
  light_switch: !input light_switch
  person_sensor: !input person_sensor
  media_player: !input media_player

  alarm_on_days: !input alarm_on_days
  alarm_on_options: !input alarm_on_options

  set_kettle_before_alarm: !input set_kettle_before_alarm
  set_light_before_alarm: !input set_light_before_alarm
  set_music_before_alarm: !input set_music_before_alarm

  set_temperature_boil: !input set_temperature_boil
  set_temperature_heat: !input set_temperature_heat

  person_home_enabled: "{{ person_home }}"
  kettle_enabled: "{{ 'on_kettle' in alarm_on_options }}"
  light_enabled: "{{ 'on_light' in alarm_on_options }}"
  phrase_enabled: "{{ 'on_phrase' in alarm_on_options }}"
  music_enabled: "{{ 'on_music' in alarm_on_options }}"

  set_command_base: !input set_command_base
  set_command_music: !input set_command_music

  invalid_states:
    - ''                    
    - 'unavailable'         
    - 'unknown'             
    - 'none'                
    - 'None'                
    - 'null'         

variables:
  light_before_alarm_in_seconds: |
    {{ set_light_before_alarm.split(':')[0] | int * 3600 + set_light_before_alarm.split(':')[1] | int * 60 + set_light_before_alarm.split(':')[2] | int }}
  light_delay_seconds: "{{ ((light_before_alarm_in_seconds | int / 254) | round(3) | string).split('.')[0] | int }}"  
  light_delay_milliseconds: "{{ ((light_before_alarm_in_seconds | int / 254) | round(3) | string).split('.')[1] | int }}"  

  # commands_music: |
  #   {{ (set_command_music | regex_replace('\\s+', ' ', true) | replace('; ', ';')).split(';') | list }}
  # commands_music_count: "{{ commands_music | count }}"
  # command_music: "{{ set_command_base ~ ' ' ~ commands_music[range(0, commands_music_count)|random] }}"

triggers:
  - trigger: template
    id: kettle_on
    value_template: >-
      {% set time_alarm = set_time_alarm %}
      {% set before_alarm = set_kettle_before_alarm %}
      {{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(today_at(time_alarm)) - as_timestamp(today_at(before_alarm))) | timestamp_custom('%H:%M', false) }}
    enabled: "{{ kettle_enabled }}"

  - trigger: template
    id: light_on
    value_template: >-
      {% set time_alarm = set_time_alarm %}
      {% set before_alarm = set_light_before_alarm %}
      {{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(today_at(time_alarm)) - as_timestamp(today_at(before_alarm))) | timestamp_custom('%H:%M', false) }}
    enabled: "{{ light_enabled }}"

  - trigger: template
    id: music_on
    value_template: >-
      {% set time_alarm = set_time_alarm %}
      {% set before_alarm = set_music_before_alarm %}
      {{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(today_at(time_alarm)) - as_timestamp(today_at(before_alarm))) | timestamp_custom('%H:%M', false) }}
    enabled: "{{ music_enabled }}"

  - trigger: template
    id: phase_on
    value_template: >-
      {% set time_alarm = set_time_alarm %}
      {{ as_timestamp(now()) | timestamp_custom("%H:%M") == as_timestamp(today_at(time_alarm)) | timestamp_custom('%H:%M', false) }}
    enabled: "{{ phrase_enabled }}"

conditions:
  - condition: template
    value_template: |
      {% set i = namespace(cnt=int(0)) %}
      {% for person in person_sensor %}
      {% set i.cnt = i.cnt + (1 if is_state(person,'home') else 0) | int %}
      {% endfor %}
      {{ true if not person_home_enabled else i.cnt > 0 }}

actions:
  - choose:
      - conditions: # Чайник на кипячение
          - condition: trigger
            id:
              - kettle_on
          - condition: template
            value_template: |
              {{ now().strftime('%a') | lower in alarm_on_days }}
        sequence: 
          - target:
              entity_id: !input kettle_switch
            data:
              temperature: "{{ set_temperature_heat | int }}"
            action: water_heater.set_temperature
          - target:
              entity_id: !input kettle_switch
            data:
              operation_mode: |
                {{ 'boil_heat' if (state_attr(kettle_switch,'current_temperature') | int < 45 | int) else 'heat' }}
            action: water_heater.set_operation_mode

      - conditions: # Ночник
          - condition: trigger
            id:
              - light_on
          - condition: template
            value_template: |
              {{ now().strftime('%a') | lower in alarm_on_days }}
        sequence: 
          - repeat:
              count: 254
              sequence:
                - data:
                    brightness: "{{ 254 / (254-1) * (repeat.index-1) + 1 }}"
                    color_temp_kelvin: 2000
                  action: light.turn_on
                  target:
                    entity_id: !input light_switch
                  continue_on_error: true
                - delay: 
                    seconds: "{{ light_delay_seconds }}"
                    milliseconds: "{{ light_delay_milliseconds }}"

      - conditions: # Музыка
          - condition: trigger
            id:
              - music_on
          - condition: template
            value_template: |
              {{ now().strftime('%a') | lower in alarm_on_days }}
        sequence: 
          - delay:
            seconds: 1
          # - service: media_player.play_media
          #   entity_id: !input media_player
          #   data:
          #     media_content_id: "{{ command_music }}"
          #     media_content_type: command
          #     extra:
          #       volume_level: 0.3
        
      - conditions: # Фраза
          - condition: trigger
            id:
              - phrase_on
          - condition: template
            value_template: |
              {{ now().strftime('%a') | lower in alarm_on_days }}
        sequence: 
          - delay:
            seconds: 1
          # - service: media_player.play_media
          #   entity_id: !input media_player
          #   data:
          #     media_content_id: !input set_phrase
          #     media_content_type: text  
          #     extra:
          #       volume_level: 0.8

mode: parallel
max: 5
