blueprint:
  name: Управление кнопкой освещением
  description: |
    ### Управление кнопкой.
    <small>Версия 2026.06.01 Сборка 1</small> 

    <small><a href="https://github.com/S0ft0r/ha-blueprints/blob/main/as-is.md">Отказ от ответственности</a></small>
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/other/dev/dev.knob.yaml
  author: Softor

  input:
    knob_device:
      name: Кнопка
      description: |
        Кнопка
      default: 
      selector:
        device:
          entity:
            - integration: mqtt
          multiple: false
    light_device:
      name: Лампа
      description: |
        Лампа
      default: 
      selector:
        entity:
          filter:
            - domain:
              - light
          multiple: false

    option_section:
      input:
        extra:
          name: Режимы работы 
          description: Режимы работы автоматизации
          default: 
            - extra_brightness
          selector:
            select:
              options:
                - label: Изменение яркости
                  value: extra_brightness
                - label: Изменение цвета
                  value: extra_color
              sort: false
              multiple: true
              custom_value: false
              mode: list
        options:
          name: Режим изменения цвета
          description: Режим изменения цвета
          selector:
            choose:
              choices:
                'случайный':
                  selector:
                    boolean:
                'последовательный':
                  selector:
                    entity:
                      filter:
                        - domain: 
                            - input_number
                      multiple: false

    mqtt_section:
      name: Настройки кнопки
      icon: mdi:dip-switch
      collapsed: true
      input:
        basic_topic:
          name: Базовый топик
          description: |
            Базовый топик устройства, подключенного через MQTT. Обычно это <strong><em>zigbee2mqtt/+/action</em></strong>, где вместо знака + будет АВТОМАТИЧЕСКИ подставлено имя выключателя/слайдера.
             + <small>При выборе устройства, подключенного через ZHA, не учитывается.
          default: "zigbee2mqtt/+/action"
          selector:
            text:

        payload_toggle:
          name: Сообщение нажатия
          description: |
            Сообщение, публикуемое устройством для определения нажатия.
          default: "toggle"
          selector:
            text:

        payload_up:
          name: Сообщение поворота по часовой
          description: |
            Сообщение, публикуемое устройством для определения поворота по часовой.
          default: "brightness_step_up"
          selector:
            text:

        payload_down:
          name: Сообщение поворота против часовой
          description: |
            Сообщение, публикуемое устройством для определения поворота против часовой.
          default: "brightness_step_down"
          selector:
            text:

        payload_color_up:
          name: Сообщение поворота по часовой с нажатием
          description: |
            Сообщение, публикуемое устройством для определения поворота по часовой с нажатием.
          default: "color_temperature_step_up"
          selector:
            text:

        payload_color_down:
          name: Сообщение поворота против часовой с нажатием
          description: |
            Сообщение, публикуемое устройством для определения поворота против часовой с нажатием.
          default: "color_temperature_step_down"
          selector:
            text:

trigger_variables:
  knob_device: !input knob_device
  light_device: !input light_device

  extra: !input extra
  options: !input options

  basic_topic: !input basic_topic

  is_brightness_enabled: "{{ 'extra_brightness' in extra }}" 
  is_color_enabled: "{{ 'extra_color' in extra }}"

variables:
  rgb_colors: |
    {{ [
    '[ 0.452,0.373 ]',
    '[ 0.612,0.374 ]',
    '[ 0.677,0.319 ]',
    '[ 0.701,0.299 ]',
    '[ 0.667,0.284 ]',
    '[ 0.581,0.245 ]',
    '[ 0.477,0.196 ]', 
    '[ 0.385,0.155 ]',
    '[ 0.301,0.116 ]',
    '[ 0.217,0.077 ]',
    '[ 0.157,0.050 ]',
    '[ 0.136,0.040 ]',
    '[ 0.137,0.065 ]',
    '[ 0.141,0.137 ]',
    '[ 0.146,0.238 ]',
    '[ 0.151,0.343 ]',
    '[ 0.157,0.457 ]',
    '[ 0.164,0.591 ]',
    '[ 0.170,0.703 ]',
    '[ 0.172,0.747 ]',
    '[ 0.199,0.724 ]',
    '[ 0.269,0.665 ]',
    '[ 0.360,0.588 ]',
    '[ 0.444,0.517 ]',
    '[ 0.527,0.447 ]'
    ] }}
  count_colors: "{{ rgb_colors | count }}"  

#  light_entities: "{{ expand(light_device) | map(attribute='entity_id') | list | first }}"
  light_brightness: "{{ state_attr(light_device, 'brightness') | int(0) }}"

  chosen_options: "{{ options.active_choice }}"
  color_index: |
    {{ (range(0, count_colors) | random)
      if chosen_options == 'случайный' 
      else (0 if options.последовательный == [] else states(options.последовательный)) }}

  xy_color: "{{ rgb_colors[color_index] }}"
  
triggers:
  - trigger: mqtt
    options:
      topic: !input basic_topic
      payload: !input payload_toggle
    id: mqtt_knob_toggle_trigger

  - trigger: mqtt
    options:
      topic: !input basic_topic
      payload: !input payload_down
    id: mqtt_knob_down_trigger

  - trigger: mqtt
    options:
      topic: !input basic_topic
      payload: !input payload_up
    id: mqtt_knob_up_trigger

  - trigger: mqtt
    options:
      topic: !input basic_topic
      payload: !input payload_color_up
    id: mqtt_knob_up_color_trigger

  - trigger: mqtt
    options:
      topic: !input basic_topic
      payload: !input payload_color_down
    id: mqtt_knob_down_color_trigger

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_toggle_trigger
          - condition: state
            entity_id: !input light_device
            state: "off"
          - condition: template
            value_template: "{{ device_attr(knob_device, 'name') == trigger.topic.split('/')[1] }}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: "{{ basic_topic | replace('+', device_attr(knob_device, 'name')) }}"
              evaluate_payload: false
              qos: 0
              retain: false
              payload: ""          
          - repeat:
              count: 10
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_pct: |
                      {{ repeat.index * 10 }}
                    xy_color: |
                      {{ rgb_colors[0] if not is_color_enabled else xy_color }}
                    transition: 1
                  target:
                    entity_id: !input light_device
                # - delay:
                #     milliseconds: 100
          - delay:
              milliseconds: 500

      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_toggle_trigger
          - condition: state
            entity_id: !input light_device
            state: "on"
          - condition: template
            value_template: "{{ device_attr(knob_device, 'name') == trigger.topic.split('/')[1] }}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: "{{ basic_topic | replace('+', device_attr(knob_device, 'name')) }}"
              evaluate_payload: false
              qos: 0
              retain: false
              payload: ""          
          - action: light.turn_off
            metadata: {}
            target:
              entity_id: !input light_device
          - delay:
              milliseconds: 500

      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_down_trigger
          - condition: state
            entity_id: !input light_device
            state: "on"
          - condition: template
            value_template: |
              {{ is_brightness_enabled }}
          - condition: template
            value_template: "{{ device_attr(knob_device, 'name') == trigger.topic.split('/')[1] }}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: "{{ basic_topic | replace('+', device_attr(knob_device, 'name')) }}"
              evaluate_payload: false
              qos: 0
              retain: false
              payload: ""          
          - action: light.turn_on
            metadata: {}
            data:
              brightness: |
                {% set bc = light_brightness | float(0) %} 
                {% set nc = bc - 25.5 %}
                {{ 1 if nc < 25.5 else nc }}
              transition: 1
            target:
              entity_id: !input light_device
          - delay:
              milliseconds: 500

      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_up_trigger
          - condition: state
            entity_id: !input light_device
            state: "on"
          - condition: template
            value_template: |
              {{ is_brightness_enabled }}
          - condition: template
            value_template: "{{ device_attr(knob_device, 'name') == trigger.topic.split('/')[1] }}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: "{{ basic_topic | replace('+', device_attr(knob_device, 'name')) }}"
              evaluate_payload: false
              qos: 0
              retain: false
              payload: ""          
          - action: light.turn_on
            metadata: {}
            data:
              brightness: |
                {% set bc = light_brightness | float(255) %} 
                {% set nc = bc + 25.5 %}
                {{ 255 if nc > 255 else nc }}
              transition: 1
            target:
              entity_id: !input light_device
          - delay:
              milliseconds: 500

      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_up_color_trigger
          - condition: state
            entity_id: !input light_device
            state: "on"
          - condition: template
            value_template: |
              {{ is_color_enabled }}
          - condition: template
            value_template: "{{ device_attr(knob_device, 'name') == trigger.topic.split('/')[1] }}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: "{{ basic_topic | replace('+', device_attr(knob_device, 'name')) }}"
              evaluate_payload: false
              qos: 0
              retain: false
              payload: ""          
          - action: light.turn_on
            metadata: {}
            data:
              xy_color: |
                {{ xy_color }}
              transition: 1
            target:
              entity_id: !input light_device
          - delay:
              milliseconds: 500

      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_down_color_trigger
          - condition: state
            entity_id: !input light_device
            state: "on"
          - condition: template
            value_template: |
              {{ is_color_enabled }}
          - condition: template
            value_template: "{{ device_attr(knob_device, 'name') == trigger.topic.split('/')[1] }}"
        sequence:
          - action: mqtt.publish
            metadata: {}
            data:
              topic: "{{ basic_topic | replace('+', device_attr(knob_device, 'name')) }}"
              evaluate_payload: false
              qos: 0
              retain: false
              payload: ""          
          - action: light.turn_on
            metadata: {}
            data:
              xy_color: |
                {{ xy_color }}
              transition: 1
            target:
              entity_id: !input light_device
          - delay:
              milliseconds: 500

mode: single
