blueprint:
  name: Управление кнопкой освещением
  description: |
    ### Управление кнопкой.
    <small>Версия 2026.06.01 Сборка 1</small> 

    <small><a href="https://github.com/S0ft0r/ha-blueprints/blob/main/as-is.md">Отказ от ответственности</a></small>
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/other/dev/dev.knob.yaml
  author: Softor

  input:
    knob_device:
      name: Кнопка
      description: |
        Кнопка
      default: 
      selector:
        device:
          entity:
            - integration: mqtt
#                - integration: zha
          multiple: false
    light_device:
      name: Лампа
      description: |
        Лампа
      default: 
      selector:
        entity:
          filter:
            - domain:
              - light
          multiple: false

    mqtt_section:
      name: Настройки кнопки
      icon: mdi:dip-switch
      input:
        basic_topic:
          name: Базовый топик
          description: |
            Базовый топик устройства, подключенного через MQTT. Обычно это <strong><em>zigbee2mqtt/+/action</em></strong>, где вместо знака + будет АВТОМАТИЧЕСКИ подставлено имя выключателя/слайдера.
             + <small>При выборе устройства, подключенного через ZHA, не учитывается.
          default: "zigbee2mqtt/+/action"
          selector:
            text:

        payload_toggle:
          name: Сообщение нажатия
          description: |
            Сообщение, публикуемое устройством для определения нажатия.
          default: "toggle"
          selector:
            text:

        payload_up:
          name: Сообщение поворота по часовой
          description: |
            Сообщение, публикуемое устройством для определения поворота по часовой.
          default: "brightness_step_up"
          selector:
            text:

        payload_down:
          name: Сообщение поворота против часовой
          description: |
            Сообщение, публикуемое устройством для определения поворота против часовой.
          default: "brightness_step_down"
          selector:
            text:

        payload_color_up:
          name: Сообщение поворота по часовой с нажатием
          description: |
            Сообщение, публикуемое устройством для определения поворота по часовой с нажатием.
          default: "color_temperature_step_up"
          selector:
            text:

        payload_color_down:
          name: Сообщение поворота против часовой с нажатием
          description: |
            Сообщение, публикуемое устройством для определения поворота против часовой с нажатием.
          default: "color_temperature_step_down"
          selector:
            text:

trigger_variables:
  knob_device: !input knob_device
  light_device: !input light_device
  
triggers:
  - trigger: mqtt
    options:
      topic: !input basic_topic
      payload: !input payload_toggle
    id: mqtt_knob_toggle_trigger

  - trigger: mqtt
    options:
      topic: !input basic_topic
      payload: !input payload_down
    id: mqtt_knob_down_trigger

  - trigger: mqtt
    options:
      topic: !input basic_topic
      payload: !input payload_up
    id: mqtt_knob_up_trigger

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_toggle_trigger
          - condition: state
            entity_id: !input light_device
            state: "off"
        sequence:
          - repeat:
              count: 5
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_pct: |
                      {{ repeat.index * 20 }}
                  target:
                    entity_id: !input light_device
                - delay:
                    milliseconds: 50

      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_toggle_trigger
          - condition: state
            entity_id: !input light_device
            state: "on"
        sequence:
          - repeat:
              count: 5
              sequence:
                - action: light.turn_off
                  metadata: {}
                  target:
                    entity_id: !input light_device

      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_down_trigger
          - condition: state
            entity_id: !input light_device
            state: "on"
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness: |
                {% set bc = state_attr(light_device, 'brightness') | float(0) %} 
                {% set nc = bc - 25.5 %}
                {{ 1 if nc < 25.5 else nc }}
            target:
              entity_id: !input light_device

      - conditions:
          - condition: trigger
            id: 
              - mqtt_knob_up_trigger
          - condition: state
            entity_id: !input light_device
            state: "on"
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness: |
                {% set bc = state_attr(light_device, 'brightness') | float(255) %} 
                {% set nc = bc + 25.5 %}
                {{ 255 if nc > 255 else nc }}
            target:
              entity_id: !input light_device

