blueprint:
  name: Управление жалюзи
  description: Управление жалюзи по времени, солнцу, слайдеру
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/loggia/covers.yaml
  author: Softor

  input:
    blind:
      name: Жалюзи
      description: Какими жалюзи необходимо управлять?
      selector:
        entity:
          filter:
            - domain: 
              - cover
          reorder: false
          multiple: true

    automation_section:
      name: Настройки автоматизации
      icon: mdi:window-shutter-cog
      collapsed: false
      input:
        automation_options:
          name: Настройки управления жалюзи
          description: Выбор между открытием/закрытием жалюзи по времени и по рассвету/закату солнца.
          default:
            - options_sun
          selector:
            select:
              options:
                - label: Открытие/закрытие по времени
                  value: options_time
                - label: Открытие/закрытие по солнцу
                  value: options_sun
              multiple: false
              sort: false
              custom_value: false

    time_section:
      name: "Настройки управления по времени"
      icon: mdi:clock-time-eight-outline
      input:
        set_up_time:
          name: Открыть жалюзи в
          default: "08:00:00"
          selector:
            time: {}
        set_down_time:
          name: Закрыть жалюзи в
          default: "20:00:00"
          selector:
            time: {}

    options_section:
      name: "Дополнительные настройки"
      icon: mdi:cog
      input:
        down_limit:
          name: Нижний предел
          description: "Нижний предел при закрытии жалюзи - если нет нужды закрывать жалюзи до конца."
          default: 0
          selector:
            number:
              min: 0
              max: 100
              step: 1
              unit_of_measurement: "%"
              mode: slider

trigger_variables:
  is_automation_time_enabled:  "{{ 'options_time' in automation_options }}"
  is_automation_sun_enabled:   "{{ 'options_sun'  in automation_options }}"

triggers:
  - trigger:  time
    at:       !input set_up_time
    id:       up_time_trigger
#    enabled:  "{{ is_automation_time_enabled }}"

  - trigger:  time
    at:       !input set_down_time
    id:       down_time_trigger
#    enabled:  "{{ is_automation_time_enabled }}"


# conditions:
#   - condition: and
#     conditions:
#       - condition: state
#         entity_id: input_boolean.cover_balcony_auto
#         state:
#           - "on"
#       - condition: state
#         entity_id: input_boolean.cover_balcony_time
#         state:
#           - "on"

actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - up_time_trigger
        sequence:
          - action: cover.set_cover_position
            metadata: {}
            target:
              entity_id: !input blind
            data:
              position: 99

      - conditions:
          - condition: trigger
            id:
              - down_time_trigger
        sequence:
          - action: cover.set_cover_position
            metadata: {}
            target:
              entity_id: !input blind
            data:
              position: !input down_limit

mode: single
