blueprint:
  name: Управление жалюзи
  description: Управление жалюзи по времени, солнцу, слайдеру
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/loggia/covers.yaml
  author: Softor
  input:
    blind:
      name: Жалюзи
      description: Какими жалюзи необходимо управлять?
      selector:
        entity:
          filter:
          - domain:
            - cover
          reorder: false
          multiple: false
    oprions:
      name: Настройки автоматизации
      icon: mdi:window-shutter-cog
      collapsed: false
      input:
        feature:
          name: Настройки управления жалюзи
          description: Какое-то объяснение
          default:
          - auto_sun_enabled
          selector:
            select:
              options:
              - label: Открытие по времени
                value: feature_up_enabled
              - label: Закрытие по времени
                value: feature_down_enabled
              - label: Открытие/закрытие по солнцу
                value: feature_sun_enabled
              - label: Защита от прямых лучей солнца
                value: feature_sun_protect
              multiple: true
              sort: false
              custom_value: false
              mode: list
        extra:
          name: Дополнительные настройки
          description: Какое-то объяснение для дополнительных настроек
          default: []
          selector:
            select:
              options:
              - label: Задержка открытия до срабатывания будильника
                value: extra_sun_pause_enabled
              - label: Ограничение закрытия жалюзи %
                value: extra_limit_down
              - label: Учитывать погодный прогноз 
                value: extra_limit_down
              sort: false
              multiple: true
              custom_value: false
              mode: list
    helpers:
      name: "Вспомогательное"
      input:
        set_up_time:
          name: Время открытия жалюзи
          default: "08:00:00"
          selector:
            time: {}
        set_down_time:
          name: Время Закрытия жалюзи
          default: "20:00:00"
          selector:
            time: {}
        down_limit:
          name: Нижний предел 
          description: "Нижний предел при закрытии жалюзи"
          default: 0
          selector:
            number:
              min: 0
              max: 100
              step: 1
              unit_of_measurement: '%'
              mode: slider
        sun_azimut:
          name: Азимут солнца
          description: "При защите от прямых лучей солнца для автоматического закрытия жалюзи"
          default: 0
          selector:
            number:
              min: 0
              max: 359
              step: 1
              unit_of_measurement: '°'
              mode: slider
        alarm_sensor:
          name: Не поднимать до
          description: >-
            Датчик, определяющий время срабатывания будильника
          selector:
            entity:
              filter:
              - domain: sensor
                device_class: timestamp
              multiple: false
        alarm_time:
          name: Задержка открытия
          description: "Задержка открытия жалюзи после срабатывание будильника"
          default: "00:10:00"
          selector:
            time: {}
        sun_elevation:
          name: Высота солнца
          description: "При защите от прямых лучей солнца для автоматического открытия жалюзи"
          default: 0
          selector:
            number:
              min: 0
              max: 45
              step: 1
              unit_of_measurement: '°'
              mode: slider
        forecast_sensor:
          name: Прогнозный сенсор
          description: >-
            Сенсор, определяющий прогноз погоды
          selector:
            entity:
              filter:
              - domain: weather
              multiple: false
    forecast:
      name: "Погода"
      description: "Прогноз погоды, при котором управляются жалюзи"
      input:
        forecasts:
          selector:
            select:
              options:
              - label: Облачно
                value: cloudy
              - label: Туман
                value: fog
              - label: Град
                value: hail
              - label: Гроза
                value: lightning
              - label: Дождь с грозой
                value: lightning-rainy
              - label: Переменная облачность
                value: partlycloudy
              - label: Ливень
                value: pouring
              - label: Дождливо
                value: rainy
              - label: Снег
                value: snowy
              - label: Дождь со снегом
                value: snowy-rainy
              - label: Ясно
                value: sunny
              sort: false
              multiple: true
              custom_value: false
              mode: list


#trigger_variables:
         

trigger:
  platform: state
  entity_id: sun.sun
  from: 'off'
  to: 'on'
action:
  service: light.turn_on
  target: light.light
          
mode: restart
max_exceeded: silent