blueprint:
  name: Управление жалюзи
  description: Управление жалюзи по времени, солнцу, слайдеру
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/loggia/covers.yaml
  author: Softor
  input:
    blind:
      name: Жалюзи
      description: Какими жалюзи необходимо управлять?
      selector:
        entity:
          filter:
          - domain:
            - cover
          reorder: false
          multiple: false
    feature_section:
      name: Настройки автоматизации
      icon: mdi:window-shutter-cog
      collapsed: false
      input:
        auto_options:
          name: Настройки управления жалюзи
          description: Какое-то объяснение
          default:
          - auto_sun_enabled
          selector:
            select:
              options:
              - label: Открытие по времени
                value: auto_up_enabled
              - label: Закрытие по времени
                value: auto_down_enabled
              - label: Открытие/закрытие по солнцу
                value: auto_sun_enabled
              - label: Защита от прямых лучей солнца
                value: auto_sun_protect
              multiple: true
              sort: false
              custom_value: false
              mode: list
        individual_config:
          name: Дополнительные настройки
          description: Какое-то объяснение для дополнительных настроек
          default: []
          selector:
            select:
              options:
              - label: Задержка открытия до срабатывания будильника
                value: auto_sun_pause_enabled
              - label: Ограничение закрытия жалюзи %
                value: auto_limit_down
              sort: false
              multiple: false
              custom_value: false
    helpers:
      name: "Вспомогательное"
      input:
        down_limit:
          name: Нижний предел 
          description: "Нижний предел при закрытии жалюзи"
          default: 0
          selector:
            number:
              min: 0
              max: 100
              step: 1
              unit_of_measurement: '%'
              mode: slider
        sun_azimut:
          name: Азимут солнца
          description: "При защите от прямых лучей солнца для автоматического закрытия жалюзи"
          default: 0
          selector:
            number:
              min: 0
              max: 359
              step: 1
              unit_of_measurement: '°'
              mode: slider
        alarm_sensor:
          name: Не включать до
          description: >-
            Датчик, определяющий время срабатывания будильника
          selector:
            entity:
              filter:
              - domain: sensor
                device_class: timestamp
              multiple: false
        alarm_time:
          name: Задержка открытия
          description: "Задержка открытия жалюзи после срабатывание будильника"
          default: "00:10:00"
          selector:
            time: {}          
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: sun.sun
  from: 'off'
  to: 'on'
action:
  service: light.turn_on
  target: light.light
