blueprint:
  name: Управление подсветкой цветов
  description: |
    Управление подсветкой цветов по времени, положению солнца или по положению штор. 
     * Версия 2026.05.00 <small>Сборка 4</small> 
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/loggia/phytolamp.yaml
  author: Softor
  
  input:
    phytolamp:
      name: Подсветка
      description: Какими лампами / реле включения ламп необходимо управлять?
      selector:
        entity:
          filter: 
            - domain: 
              - light
              - switch
          reorder: false
          multiple: true

    automation_section:
      name: Настройки автоматизации
      icon: mdi:window-shutter-cog
      collapsed: false
      input:
        automation_options:
          name: Настройки управления подсветкой
          description: | 
            Выбор между включением/выключением подсветкой по времени или по рассвету/закату солнца.
          default:
            - options_sun
          selector:
            select:
              options:
                - label: Включение/выключение по времени
                  value: options_time
                - label: Включение/выключение по солнцу
                  value: options_sun
                - label: Включение/выключение по положению штор
                  value: options_blind
              multiple: false
              sort: false
              custom_value: false

        automation_extra:
          name: Дополнительные настройки
          description: Дополнительные настройки автоматизации
          default: []
          selector:
            select:
              options:
                # - label: Задержка открытия до срабатывания будильника
                #   value: extra_alarm_pause
                # - label: Ограничение закрытия штор %
                #   value: extra_limit_down
                - label: Учитывать положение солнца для выключения подсветки
                  value: extra_sun_position_off
                - label: Учитывать положение солнца для включения подсветки
                  value: extra_sun_position_on
                - label: Учитывать прогноз погоды  
                  value: extra_forecast
              sort: false
              multiple: true
              custom_value: false
              mode: list

        forecast_sensor:
          name: Прогнозный сенсор
          description: |
            Сенсор, определяющий прогноз погоды.
              * Параметр обязателен только при выборе параметра <em>"Учитывать прогноз погоды"</em>.
              Если ничего не выбрано, то дополнительный параметр учитываться не будет.
          default: []
          selector:
            entity:
              filter:
                - domain: 
                  - weather
              multiple: false

    time_section:
      name: Настройки управления по времени
      description: |
        Устанавливается время включения/выключения подсветки.        
      icon: mdi:clock-time-eight-outline
      input:
        set_on_time:
          name: Включить подсветку в
          default: "08:00:00"
          selector:
            time: {}
        set_on_time_sensor:
          name: Включить подсветку по сенсору
          description: |
            Сенсор, определяющий время включения подсветки.
              * При выборе сенсора, время включения подсветки, заданное в проекте, учитываться не будет.
          default: []
          selector:
            entity:
              filter:
                - domain: 
                  - input_datetime
              multiple: false
        set_off_time:
          name: Выключить подсветку в
          default: "20:00:00"
          selector:
            time: {}
        set_off_time_sensor:
          name: Выключить подсветку по сенсору
          description: |
            Сенсор, определяющий время выключения подсветки.
              * При выборе сенсора, время выключения подсветки, заданное в проекте, учитываться не будет.
          default: []
          selector:
            entity:
              filter:
                - domain: 
                  - input_datetime
              multiple: false

    sun_section:
      name: "Настройки управления по солнцу"
      icon: mdi:weather-sunny
      input:
        sun_sensor:
          name: "Датчик солнца"
          description: >-
            Датчик, по которому определяется положение солнца
          default: "sun.sun"
          selector:
            entity:
              filter:
                - domain:
                    - sun
              multiple: false

        sun_azimuth:
          name: Азимут солнца
          description: |
            Угол между направлением на север и направлением на солнце. 
              * Для автоматического выключения подсветки при включенном параметре <em>"Учитывать положение солнца"</em> .
          default: 0
          selector:
            number:
              min: 0
              max: 359
              step: 1
              unit_of_measurement: '°'
              mode: slider
        
        sun_azimuth_sensor:
          name: Сенсор азимута солнца
          description: |
            Сенсор, определяющий азимут солнца для выключения подсветки.
              * При выборе сенсора, азимут солнца, заданный в проекте, учитываться не будет.
          default: []
          selector:
            entity:
              filter:
                - domain: 
                  - input_number
              multiple: false

        sun_elevation:
          name: Высота солнца
          description: |
            Угол возвышения солнца над горизонтом. 
              * Для автоматического включения подсветки при включенном параметре <em>"Учитывать положение солнца"</em> .
          default: 0
          selector:
            number:
              min: 0
              max: 45
              step: 1
              unit_of_measurement: '°'
              mode: slider

        sun_elevation_sensor:
          name: Сенсор высоты солнца
          description: |
            Сенсор, определяющий высоту солнца для включения подсветки.
              * При выборе сенсора, высота солнца, заданная в проекте, учитываться не будет.
          default: []
          selector:
            entity:
              filter:
                - domain: 
                  - input_number
              multiple: false

    options_section:
      name: "Дополнительные настройки"
      icon: mdi:cog
      input:
        forecasts:
          name: Прогноз погоды
          description: |
            Прогноз погоды, при котором будет активна защита от попадания прямых лучей 
          default: 
            - sunny
            - partlycloudy
          selector:
            select:
              options:
                - label: Ясно
                  value: sunny
                - label: Переменная облачность
                  value: partlycloudy
                - label: Облачно
                  value: cloudy
                - label: Туман
                  value: fog
              sort: false
              multiple: true
              custom_value: false
              mode: list


              
trigger_variables:
  automation_options:             !input automation_options
  automation_extra:               !input automation_extra

  phytolamp:                      !input phytolamp

  set_on_time_sensor:             !input set_on_time_sensor
  set_off_time_sensor:            !input set_off_time_sensor
  forecast_sensor:                !input forecast_sensor
  sun_sensor:                     !input sun_sensor
  sun_elevation_sensor:           !input sun_elevation_sensor
  sun_azimuth_sensor:             !input sun_azimuth_sensor

  set_on_time:                    !input set_on_time
  set_off_time:                   !input set_off_time
  forecasts:                      !input forecasts
  sun_azimuth:                    !input sun_azimuth
  sun_elevation:                  !input sun_elevation

   
  is_automation_time_enabled:     "{{ 'options_time' in automation_options }}"
  is_automation_sun_enabled:      "{{ 'options_sun' in automation_options }}"
  is_automation_blind_enabled:    "{{ 'options_blind' in automation_options }}"

  is_forecast_enabled:            "{{ forecast_sensor != [] and 'extra_forecast' in automation_extra }}"
  is_sun_position_on_enabled:     "{{ sun_sensor != [] and 'extra_sun_position_on' in automation_extra }}"
  is_sun_position_off_enabled:    "{{ sun_sensor != [] and 'extra_sun_position_off' in automation_extra }}"

  on_time:  | 
                                  {{ as_timestamp(today_at(set_on_time)) | timestamp_custom("%H:%M") 
                                     if set_on_time_sensor == [] else 
                                     as_timestamp(now()) | timestamp_custom("%H:%M") == as_timestamp(today_at(states(set_on_time_sensor))) | timestamp_custom("%H:%M") }}

  off_time:  | 
                                  {{ as_timestamp(today_at(set_off_time)) | timestamp_custom("%H:%M") 
                                     if set_off_time_sensor == [] else 
                                     as_timestamp(now()) | timestamp_custom("%H:%M") == as_timestamp(today_at(states(set_off_time_sensor))) | timestamp_custom("%H:%M") }}

triggers:
  - trigger:        template
    value_template: |
      {{ as_timestamp(now()) | timestamp_custom("%H:%M") == on_time }}
    id:             on_time_trigger
    enabled:        "{{ is_automation_time_enabled }}"

  - trigger:        template
    value_template: |
      {{ as_timestamp(now()) | timestamp_custom("%H:%M") == off_time }}
    id:             off_time_trigger
    enabled:        "{{ is_automation_time_enabled }}"

  - trigger:        state
    entity_id:      !input forecast_sensor
    id:             forecast_trigger
    enabled:        "{{ is_forecast_enabled }}"

  - trigger:        template
    value_template: "{{ state_attr(sun_sensor,'azimuth') | float > (sun_azimuth if sun_azimuth_sensor == [] else states(sun_azimuth_sensor) | int(0)) }}"
    id:             sun_azimuth_trigger
    enabled:        "{{ is_sun_position_on_enabled }}"

  - trigger:        template
    value_template: "{{ state_attr(sun_sensor,'elevation') | float > (sun_elevation if sun_elevation_sensor == [] else states(sun_elevation_sensor) | int(0)) }}"
    id:             sun_elevation_trigger
    enabled:        "{{ is_sun_position_off_enabled }}"

actions:
  - choose:
      - conditions: # Время включения
          - condition: trigger
            id:
              - on_time_trigger
        sequence:
          - action: homeassistant.turn_on
            metadata: {}
            target:
              entity_id: !input phytolamp

      - conditions: # Время включения
          - condition: trigger
            id:
              - off_time_trigger
        sequence:
          - action: homeassistant.turn_off
            metadata: {}            
            target:
              entity_id: !input phytolamp

      - conditions: # Выключить при изменении погоды
          - condition: trigger
            id:
              - forecast_trigger
          - condition: template
            value_template: |
              {{ states(forecast_sensor) in forecasts }} 
          - condition: template
            value_template: | 
              {{ true if not is_sun_position_on_enabled else 
                state_attr(sun_sensor,'azimuth') | float > (sun_azimuth if sun_azimuth_sensor == [] else states(sun_azimuth_sensor) | int(0)) }}
          - condition: template
            value_template: | 
              {{ true if not is_sun_position_off_enabled else 
                state_attr(sun_sensor,'elevation') | float > (sun_elevation if sun_elevation_sensor == [] else states(sun_elevation_sensor) | int(0)) }}
          - condition: template
            value_template: |
              {{ true if not is_automation_time_enabled else (as_timestamp(now()) | timestamp_custom("%H:%M") >= on_time and as_timestamp(now()) | timestamp_custom("%H:%M") <= off_time) }}
        sequence:
          - action: homeassistant.turn_off
            metadata: {}            
            target:
              entity_id: !input phytolamp

      - conditions: # Включить при изменении погоды
          - condition: trigger
            id:
              - forecast_trigger
          - condition: template
            value_template: |
              {{ states(forecast_sensor) not in forecasts }} 
          - condition: template
            value_template: | 
              {{ true if not is_sun_position_on_enabled else 
                state_attr(sun_sensor,'azimuth') | float > (sun_azimuth if sun_azimuth_sensor == [] else states(sun_azimuth_sensor) | int(0)) }}
          - condition: template
            value_template: | 
              {{ true if not is_sun_position_off_enabled else 
                state_attr(sun_sensor,'elevation') | float > (sun_elevation if sun_elevation_sensor == [] else states(sun_elevation_sensor) | int(0)) }}
          - condition: template
            value_template: |
              {{ true if not is_automation_time_enabled else (as_timestamp(now()) | timestamp_custom("%H:%M") >= on_time and as_timestamp(now()) | timestamp_custom("%H:%M") <= off_time) }}
        sequence:
          - action: homeassistant.turn_on
            metadata: {}            
            target:
              entity_id: !input phytolamp

      - conditions: # Включить подсветку
          - condition: trigger
            id:
              - sun_elevation_trigger
        sequence:
          - action: homeassistant.turn_on
            metadata: {}            
            target:
              entity_id: !input phytolamp

mode: queued
max: 10
