blueprint:
  name: Тест
  description: |
    Тест
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/loggia/test.yaml
  author: Softor
  input:
    blind:
      name: Шторы
      description: Какими приводами штор необходимо управлять?
      selector:
        entity:
          filter:
            - domain: 
              - cover
          reorder: false
          multiple: true
    options_section:
      name: "Дополнительные настройки"
      icon: mdi:cog
      input:
        slider_sensor:
          name: Выключатель/слайдер
          description: |
            Выключатель типа <strong>Aqara Z1 Pro</strong> со встроенным слайдером.
          default:
          selector:
            device:
              integration: mqtt
              multiple: false
trigger_variables:
  blind:                          !input blind
  slider_sensor:                  !input slider_sensor

variables: 
  entity_name: "{{ device_attr(slider_sensor, 'name') }}"
    
triggers:
  - trigger: mqtt
    options:
      topic: "{{ 'zigbee2mqtt/' ~ entity_name ~ '/action' }}"
      payload: slider_up
    id: slider_down_trigger
    
actions:
  - choose:
      - conditions: # Закрыть по слайдеру
          - condition: trigger
            id:
              - slider_down_trigger
        sequence:
          - repeat:
              count: 1
              sequence:
                - action: cover.set_cover_position
                  metadata: {}
                  target:
                    entity_id: !input blind
                  data:
                    position: 35
                - delay:
                    seconds: 3
