blueprint:
  name: Управление системой полива
  description: |
    (МОДИФИКАЦИЯ!!!)
    Управление поливом цветов по времени, датчикам влажности. 
      Версия 2026.05.00 
      Сборка 2
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/loggia/waterpump.yaml
  author: Softor

  input:
    waterpump:
      name: Оросительная система
      description: Какими системами необходимо управлять?
      selector:
        device:
          entity:
            - domain: switch
          multiple: false
    plant:
      name: Датчик почвы
      description: Использовать датчик для определения состояния почвы
      selector:
        device:
          entity:
            - integration: plant
          multiple: false

    # automation_section:
    #   name: Настройки автоматизации
    #   icon: mdi:window-shutter-cog
    #   collapsed: false
    #   input:
    #     automation_options:
    #       name: Настройки управления орошением
    #       description: |
    #         Настройки.
    #       default:
    #         - options_time
    #       selector:
    #         select:
    #           options:
    #             # - label: Открытие/закрытие по времени
    #             #   value: options_time
    #             - label: Включать систему орошения по времени
    #               value: options_time
    #             - label: Включать по показаниям сенсора почвы
    #               value: options_plant
    #           multiple: true
    #           sort: false
    #           custom_value: false

    time_section:
      name: Настройки управления по времени
      description: |
        Устанавливается время включения системы орошения.
      icon: mdi:clock-time-eight-outline
      input:
        options_time:
          name: Включать систему орошения по времени
          default: true
          selector:
            boolean: {}
        set_plant_sensor_state:
          name: Учитывать показания сенсора почвы
          default: false
          selector:
            boolean: {}
        set_on_time_morning:
          name: Включить утром в
          default: "08:00:00"
          selector:
            time: {}
        set_on_time_evening:
          name: Включить вечером в
          default: "20:00:00"
          selector:
            time: {}
      
    plant_section:
      name: Настройки управления по показания датчика почвы
      description: |
        Настройки датчика почвы.
      icon: mdi:flower-tulip-outline
      input:
        options_plant:
          name: Включать систему орошения по показания датчика
          default: false
          selector:
            boolean: {}
        set_soil_moisture_min:
          name: Нижний предел влажности
          description: |
            Включение системы орошения при понижении предела влажности почвы.
            <small>* При включенной опции <em>Включать по показаниям сенсора почвы</em></small> 
          default: 1
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "%"
        set_soil_moisture_max:
          name: Верхний предел влажности
          description: При привышении предела влажности почвы система орошения включаться не будет.
          default: 1
          selector:
            number:
              min: 1
              max: 100
              step: 1
              mode: slider
              unit_of_measurement: "%"
        set_debounce_pause:
          name: Включить защиту от перелива
          default: false
          selector:
            boolean: {}
        set_debounce_time:
          name: Пауза перед запуском
          description: > 
            Пауза перед следующем включением автоматизации. Используется только в режиме включения по показаниям датчика почвы 
            <small>* Для защиты от перелива при медленном изменении показаний датчика почвы
          default: "00:10:00"
          selector:
            time: {}

    mode_section:
      name: Настройки режимов работы системы
      description: |
        Настройка.
      icon: mdi:cog
      input:
        set_working_day_morning:
          name: Режим включения утром
          default: every_day_morning
          selector:
            select:
              options:
                - label: Выключено
                  value: off_morning
                - label: Ежедневно
                  value: every_day_morning
                - label: Через день
                  value: every_over_day_morning
                - label: Выбор
                  value: select_morning
              mode: dropdown
        set_mode_morning:
          name: Режим работы системы утром
          default: mode_2_morning
          selector:
            select:
              options:
                - label: Однократно
                  value: mode_1_morning
                - label: Дважды с паузой
                  value: mode_2_morning
                - label: Трижды с паузой
                  value: mode_3_morning
              mode: dropdown
        set_mode_work:
          name: Включать на
          description: Время, на которе включается система орошения 
          default: 1
          selector:
            number:
              min: 1
              max: 240
              step: 1
              mode: box
              unit_of_measurement: сек
        set_working_day_evening:
          name: Режим включения вечером
          default: off_evening
          selector:
            select:
              options:
                - label: Выключено
                  value: off_evening
                - label: Ежедневно
                  value: every_day_evening
                - label: Через день
                  value: every_over_day_evening
                - label: Выбор
                  value: select_evening
              mode: dropdown
        set_mode_evening:
          name: Режим работы системы вечером
          default: mode_1_evening
          selector:
            select:
              options:
                - label: Однократно
                  value: mode_1_evening
                - label: Дважды с паузой
                  value: mode_2_evening
                - label: Трижды с паузой
                  value: mode_3_evening
              mode: dropdown
        set_mode_pause:
          name: Величина паузы
          description: Величина паузы между включениями при режимах работы с паузами 
          default: 1
          selector:
            number:
              min: 1
              max: 240
              step: 1
              mode: box
              unit_of_measurement: сек

    # rainwater_section:
    #   name: Настройки детектора дождя
    #   description: |
    #     Настройки детектора дождя.
    #   icon: mdi:weather-pouring
    #   input:
    #     rain:
    #       name: Детектор дождя
    #       description: Использовать датчик для определения дождя
    #       default: []
    #       selector:
    #         entity:
    #           filter:
    #             - domain: 
    #                 - sensor
    #               integration: mqtt
    #           multiple: false

trigger_variables:
  waterpump: !input waterpump
  plant: !input plant
#  rain: !input rain

#  automation_options: !input automation_options

  set_working_day_morning: !input set_working_day_morning
  set_working_day_evening: !input set_working_day_evening
  set_mode_morning: !input set_mode_morning
  set_mode_evening: !input set_mode_evening

  set_debounce_pause: !input set_debounce_pause
  set_debounce_time: !input set_debounce_time


  set_plant_sensor_state: !input set_plant_sensor_state
  set_soil_moisture_min: !input set_soil_moisture_min
  set_soil_moisture_max: !input set_soil_moisture_max

  options_time: !input options_time
  options_plant: !input options_plant

  is_on_time_enabled: "{{ options_time }}"
  is_plant_state_enabled: "{{ options_plant }}"

  soil_moisture_entities: "{{ (device_entities(plant) | reject('is_state', ['unavailable', 'unknown']) | select('match', 'sensor.') | select('search', 'soil_moisture') | list | join ) }}"


variables:
  waterpump_entities: "{{ device_entities(waterpump) | reject('is_state', ['unavailable', 'unknown']) | select('match', 'switch.') | list }}"

  soil_moisture_entities: "{{ (device_entities(plant) | reject('is_state', ['unavailable', 'unknown']) | select('match', 'sensor.') | select('search', 'soil_moisture') | list | join ) }}"
  temperature_entities: "{{ (device_entities(plant) | reject('is_state', ['unavailable', 'unknown']) | select('match', 'sensor.') | select('search', 'temperature') | list) | join }}"
  humidity_entities: "{{ (device_entities(plant) | reject('is_state', ['unavailable', 'unknown']) | select('match', 'sensor.') | select('search', 'air_humidity') | list) | join }}"

  mode_repeat_morning: "{{ set_mode_morning.split('_')[1] | int - 1 }}"
  mode_repeat_evening: "{{ set_mode_evening.split('_')[1] | int - 1 }}"

triggers:
  - platform: time
    at: !input set_on_time_morning
    id: on_time_morning_trigger
    enabled: "{{ is_on_time_enabled }}"

  - platform: time
    at: !input set_on_time_evening
    id: on_time_evening_trigger
    enabled: "{{ is_on_time_enabled }}"

  - platform: template
    value_template: >
      {{ false if plant == [] else states(soil_moisture_entities) | int < set_soil_moisture_min }}
    id: plant_state_trigger
    enabled: "{{ is_plant_state_enabled }}"

actions:
  - choose:
      - conditions: # Состояние почвы
          - condition: trigger
            id:
              - plant_state_trigger
        sequence:
          - repeat:
              for_each: "{{ waterpump_entities }}"
              sequence:
                - action: switch.turn_on
                  metadata: {}            
                  target:
                    entity_id: >
                      {{ repeat.item if repeat is defined else '' }}
          - delay:
              seconds: !input set_mode_work
          - repeat:
              for_each: "{{ waterpump_entities }}"
              sequence:
                - action: switch.turn_off
                  metadata: {}            
                  target:
                    entity_id: >
                      {{ repeat.item if repeat is defined else '' }}
          - if:
              - condition: template
                value_template: "{{ set_debounce_pause }}"
            then:
              - delay: 
                  hours: "{{ set_debounce_time.split(':')[0] | int(default=0) }}"
                  minutes: "{{ set_debounce_time.split(':')[1] | int(default=0) }}"
                  seconds: "{{ set_debounce_time.split(':')[2] | int(default=0) }}"

      - conditions: # Время включения утром
          - condition: trigger
            id:
              - on_time_morning_trigger
          - condition: template
            value_template: >
              {{ 'off_morning' not in set_working_day_morning }}
          - condition: template
            value_template: >
              {{ true if not set_plant_sensor_state else (states(soil_moisture_entities) | int < set_soil_moisture_max) }}
        sequence:
          - repeat:
              for_each: "{{ waterpump_entities }}"
              sequence:
                - action: switch.turn_on
                  metadata: {}            
                  target:
                    entity_id: >
                      {{ repeat.item if repeat is defined else '' }}
          - delay:
              seconds: !input set_mode_work
          - repeat:
              for_each: "{{ waterpump_entities }}"
              sequence:
                - action: switch.turn_off
                  metadata: {}            
                  target:
                    entity_id: >
                      {{ repeat.item if repeat is defined else '' }}
          - repeat:
              count: "{{ mode_repeat_morning }}"
              sequence:
                - delay:
                    seconds: !input set_mode_pause
                - repeat:
                    for_each: "{{ waterpump_entities }}"
                    sequence:
                      - action: switch.turn_on
                        metadata: {}            
                        target:
                          entity_id: >
                            {{ repeat.item if (repeat is defined and (true if not set_plant_sensor_pause else (states(soil_moisture_entities) | int < set_soil_moisture_max))) else '' }}
                - delay:
                    seconds: !input set_mode_work
                - repeat:
                    for_each: "{{ waterpump_entities }}"
                    sequence:
                      - action: switch.turn_off
                        metadata: {}            
                        target:
                          entity_id: >
                            {{ repeat.item if repeat is defined else '' }}

      - conditions: # Время включения вечером
          - condition: trigger
            id:
              - on_time_evening_trigger
          - condition: template
            value_template: >
              {{ 'off_evening' not in set_working_day_evening }}
          - condition: template
            value_template: >
              {{ true if not set_plant_sensor_state else (states(soil_moisture_entities) | int < set_soil_moisture_max) }}
        sequence:
          - repeat:
              for_each: "{{ waterpump_entities }}"
              sequence:
                - action: switch.turn_on
                  metadata: {}            
                  target:
                    entity_id: >
                      {{ repeat.item if repeat is defined else '' }}
          - delay:
              seconds: !input set_mode_work
          - repeat:
              for_each: "{{ waterpump_entities }}"
              sequence:
                - action: switch.turn_off
                  metadata: {}            
                  target:
                    entity_id: >
                      {{ repeat.item if repeat is defined else '' }}
          - repeat:
              count: "{{ mode_repeat_evening }}"
              sequence:
                - delay:
                    seconds: !input set_mode_pause
                - repeat:
                    for_each: "{{ waterpump_entities }}"
                    sequence:
                      - action: switch.turn_on
                        metadata: {}            
                        target:
                          entity_id: >
                            {{ repeat.item if (repeat is defined and (true if not set_plant_sensor_pause else (states(soil_moisture_entities) | int < set_soil_moisture_max))) else '' }}
                - delay:
                    seconds: !input set_mode_work
                - repeat:
                    for_each: "{{ waterpump_entities }}"
                    sequence:
                      - action: switch.turn_off
                        metadata: {}            
                        target:
                          entity_id: >
                            {{ repeat.item if repeat is defined else '' }}

mode: single
