blueprint:
  name: Управление системой полива
  description: |
    Управление поливом цветов по времени, датчикам влажности. 
      Версия 2026.05.00 
      Сборка 1
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/loggia/waterpump.yaml
  author: Softor

  input:
    waterpump:
      name: Оросительная система
      description: Какими системами необходимо управлять?
      selector:
        device:
          entity:
            - domain: switch
          multiple: false

    plant_section:
      name: Настройки датчика почвы
      description: |
        Устанавливается время включения системы орошения.
      icon: mdi:flower-tulip-outline
      input:
        plant:
          name: Датчик почвы
          description: Использовать датчик для определения состояния почвы
          selector:
            device:
              entity:
                - integration: plant
              multiple: false
  
    automation_section:
      name: Настройки автоматизации
      icon: mdi:window-shutter-cog
      collapsed: false
      input:
        automation_options:
          name: Настройки управления орошением
          description: |
            Настройки.
          default:
            - options_morning
          selector:
            select:
              options:
                # - label: Открытие/закрытие по времени
                #   value: options_time
                - label: Включать систему орошения утром
                  value: options_morning
                - label: Включать систему орошения вечером
                  value: options_evening
                - label: Учитывать показания сенсора почвы
                  value: options_plant
              multiple: true
              sort: false
              custom_value: false

    time_section:
      name: Настройки управления по времени
      description: |
        Устанавливается время включения системы орошения.
      icon: mdi:clock-time-eight-outline
      input:
        set_on_time_morning:
          name: Включить утром в
          default: "08:00:00"
          selector:
            time: {}
        set_on_time_evening:
          name: Включить вечером в
          default: "20:00:00"
          selector:
            time: {}
      
trigger_variables:
  waterpump: !input waterpump
  plant: !input waterpump

#  set_on_time_morning: !input set_on_time_morning
#  set_on_time_evening: !input set_on_time_evening

  waterpump_entities: "{{ device_entities(waterpump) | reject('is_state', ['unavailable', 'unknown']) | select('match', 'switch.') | list }}"

  soil_moisture: "{{ device_entities(plant) | reject('is_state', ['unavailable', 'unknown']) | select('match', 'sensor.') | select('match', 'soil') | list }}"
  temperature: "{{ device_entities(plant) | reject('is_state', ['unavailable', 'unknown']) | select('match', 'sensor.') | select('match', 'temperature') | list }}"

triggers:
  - platform: time
    at: !input set_on_time_morning
    id: on_time_morning_trigger

  - platform: time
    at: !input set_on_time_evening
    id: on_time_evening_trigger

actions:
  - choose:
      - conditions: # Время включения
          - condition: trigger
            id:
              - on_time_morning_trigger
            sequence:
              # - repeat:
              #     for_each: >
              #       {% set waterpump = "3f2ba924cfd842a6b67a21bc4bf7aa92" %}
              #       {{ device_entities(waterpump) | reject("is_state", ["unavailable",
              #       "unknown"]) | select("match", "switch.") | list }}
              #     sequence:
              #       - action: switch.turn_off
              #         metadata: {}
              #         data: {}
              #         target:
              #           entity_id: |
              #             {{ repeat.item if repeat is defined else '' }}
              - repeat:
                  for_each: >
                    {{ waterpump_entities }}
                  sequence:
                    - action: switch.turn_on
                      metadata: {}            
                      target:
                        entity_id: >
                          {{ repeat.item if repeat is defined else '' }}
              - delay:
                  seconds: 1
              - repeat:
                  for_each: >
                    {{ waterpump_entities }}
                  sequence:
                    - action: switch.turn_off
                      metadata: {}            
                      target:
                        entity_id: >
                          {{ repeat.item if repeat is defined else '' }}

      - conditions: # Время включения
          - condition: trigger
            id:
              - on_time_evening_trigger
            sequence:
              - repeat:
                  for_each: >
                    {{ waterpump_entities }}
                  sequence:
                    - action: switch.turn_on
                      metadata: {}            
                      target:
                        entity_id: >
                          {{ repeat.item if repeat is defined else '' }}
              - delay:
                  seconds: 1
              - repeat:
                  for_each: >
                    {{ waterpump_entities }}
                  sequence:
                    - action: switch.turn_off
                      metadata: {}            
                      target:
                        entity_id: >
                          {{ repeat.item if repeat is defined else '' }}

mode: single

