blueprint:
  name: Управление подсветкой растений
  description: |
    ### Управление подсветкой растений по положению солнца.
    <small>Версия 2026.05.01 Сборка 1</small> 
    <small><a href="https://4pda.to/forum/index.php?showtopic=871505&view=findpost&p=143572987">Специально для 4PDA</a></small>
    **Особенности:**
     + Отсрочка включения подсветкой растений до определенного времени после рассвета 
     + Установка времени выключения подсветки в определенное время до заката
     + Управление включение/выключением подсветки по поожению солнца
     + Учитывается прогноз погоды и/или датчик освещенности 
     + Использование внешних сенсоров для некоторых параметров
     + Добавлена установка паузы для защиты от часто срабатывающего датчика освещения (например, Xiaomi BLE)
    <small><a href="https://github.com/S0ft0r/ha-blueprints/blob/main/as-is.md">Отказ от ответственности</a></small>
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/loggia/dev/dev.phytolamp.yaml
  author: Softor

  input:
    phytolamp:
      name: Устройства включения/лампы подсветки
      description: Какими устройствами включения/лампы подсветки необходимо управлять?
      selector:
        entity:
          filter:
            - domain:
                - switch
                - light
          reorder: false
          multiple: true

    sun_sensor:
      name: Датчик солнца
      description: Датчик, по которому определяется положение солнца
      default: "sun.sun"
      selector:
        entity:
          filter:
            - domain:
                - sun
          multiple: false

    automation_section:
      name: Настройки автоматизации
      icon: mdi:window-shutter-cog
      collapsed: false
      input:
        automation_extra:
          name: Режимы работы 
          description: Режимы работы автоматизации
          default: []
          selector:
            select:
              options:
                - label: Включение/выключение по положнию солнца
                  value: extra_sun_position
                - label: Учитывать освещенность
                  value: extra_illuminance
                - label: Учитывать прогноз погоды
                  value: extra_forecast
                # - label: Ограничение по времени открытия
                #   value: extra_on_until
                # - label: Ограничение по времени закрытия
                #   value: extra_off_until
              sort: false
              multiple: true
              custom_value: false
              mode: list

        illuminance_sensor:
          name: Сенсор освещенности
          description: |
            Сенсор, определяющий уровень освещенности.
             + <small>Параметр обязателен только при выборе параметра <em>"Учитывать освещенность"</em> и отсутствии сенсора погоды. Если ничего не выбрано, то дополнительный параметр учитываться не будет.</small>
          default: []
          selector:
            entity:
              filter:
                - domain:
                    - sensor
                  device_class: 
                    - illuminance

        forecast_sensor:
          name: Прогнозный сенсор
          description: |
            Сенсор, определяющий прогноз погоды.
             + <small>Параметр обязателен только при выборе параметра <em>"Учитывать прогноз погоды"</em>. Если ничего не выбрано, то дополнительный параметр учитываться не будет.</small>
          default: []
          selector:
            entity:
              filter:
                - domain:
                    - weather
              multiple: false

    time_section:
      name: Настройки управления по времени
      description: |
        Устанавливается время включения/выключения подсветки.
      icon: mdi:clock-time-eight-outline
      input:
        set_on_time_workday:
          name: Включать подсветку в будни в
          default: "06:10:00"
          selector:
            time: {}

        set_on_time_weekend:
          name: Включать подсветку в выходные в
          default: "07:10:00"
          selector:
            time: {}

        set_off_time:
          name: Выключать подсветку в
          default: "21:00:00"
          selector:
            time: {}

    sun_position_section:
      name: Настройка включения/выключения по положению солнца
      icon: mdi:sun-wireless-outline
      input:
        set_sun_azimuth:
          name: Азимут солнца
          description: |
            Угол между направлением на север и направлением на солнце. 
             + <small>Для автоматического закрытия штор при включенной опции защиты от прямых лучей солнца.</small>
          default: 0
          selector:
            number:
              min: 0
              max: 359
              step: 1
              unit_of_measurement: "°"
              mode: slider

        set_sun_azimuth_sensor:
          name: Сенсор азимута солнца
          description: |
            Сенсор, определяющий азимут солнца для выключения подсветки.
             + <small>При выборе сенсора, азимут солнца, заданный в проекте, учитываться не будет.</small>
          default: []
          selector:
            entity:
              filter:
                - domain: 
                    - input_number
              multiple: false

        set_sun_elevation:
          name: Высота солнца
          description: |
            Угол возвышения солнца над горизонтом. 
             + <small>Для автоматического открытия штор при включенной защите от прямых лучей солнца.</small>
          default: 0
          selector:
            number:
              min: 0
              max: 45
              step: 1
              unit_of_measurement: "°"
              mode: slider

        set_sun_elevation_sensor:
          name: Сенсор высоты солнца
          description: |
            Сенсор, определяющий высоту солнца для открытия штор.
             + <small>При выборе сенсора, высота солнца, заданная в проекте, учитываться не будет.</small>
          default: []
          selector:
            entity:
              filter:
                - domain: 
                    - input_number
              multiple: false

    options_section:
      name: "Дополнительные настройки"
      icon: mdi:cog
      input:
        forecasts:
          name: Прогноз погоды
          description: |
            Прогноз погоды, при котором будет активна защита от попадания прямых лучей
          default:
            - sunny
            - partlycloudy
          selector:
            select:
              options:
                - label: Ясно
                  value: sunny
                - label: Переменная облачность
                  value: partlycloudy
                - label: Облачно
                  value: cloudy
                - label: Туман
                  value: fog
              sort: false
              multiple: true
              custom_value: false
              mode: list

        set_min_illuminance:
          name: Нижний порог освещенности
          description: |
            Нижний порог освещенности 
             + <small>Для открытия штор при включенной защите от попадания прямых лучей.</small>
          default: 0
          selector:
            number:
              min: 0
              max: 100000
              step: 100
              mode: box
              unit_of_measurement: "люкс"

        set_max_illuminance:
          name: Верхний порог освещенности
          description: |
            Верхний порог освещенности 
             + <small>Для закрытия штор при включенной защите от попадания прямых лучей.</small>
          default: 0
          selector:
            number:
              min: 0
              max: 100000
              step: 100
              mode: box
              unit_of_measurement: "люкс"

        set_illuminance_delay:
          name: Задержка при скачках изменений освещенности
          description: |
            Величина задержки при скачках изменений освещенности 
             + <small>Для того, чтобы отсечь очень частые пограничные изменения освещенности</small>
          default: 60
          selector:
            number:
              min: 0
              max: 600
              step: 10
              mode: slider
              unit_of_measurement: "секунд"

mode: queued
max: 10
max_exceeded: silent

trigger_variables:
  automation_extra: !input automation_extra

  phytolamp: !input phytolamp

  forecast_sensor: !input forecast_sensor
  sun_sensor: !input sun_sensor
  illuminance_sensor: !input illuminance_sensor

  forecasts: !input forecasts
  set_sun_azimuth: !input set_sun_azimuth
  set_sun_azimuth_sensor: !input set_sun_azimuth_sensor
  set_sun_elevation: !input set_sun_elevation
  set_sun_elevation_sensor: !input set_sun_elevation_sensor
  set_on_time_workday: !input set_on_time_workday
  set_on_time_weekend: !input set_on_time_weekend
  set_off_time: !input set_off_time
  set_min_illuminance: !input set_min_illuminance
  set_max_illuminance: !input set_max_illuminance
  set_illuminance_delay: !input set_illuminance_delay

  # is_forecast_enabled: "{{ forecast_sensor != [] and 'extra_forecast' in automation_extra }}"
  # is_illuminance_enabled: "{{ illuminance_sensor != [] and (set_min_illuminance != 0 or set_max_illuminance != 0) and 'extra_illuminance' in automation_extra }}"
  # is_sun_position_enabled: "{{ 'extra_sun_position' in automation_extra }}"

variables:
  workday: "{{ now().weekday() < 5 }}"
  weekend: "{{ not workday }}"
  nextday: "{{ (now().weekday() + 1) % 7 }}"
  
  on_time: "{{ set_on_time_workday if workday else set_on_time_weekend }}"
  off_time: "{{ set_off_time }}"

  sun_azimuth: "{{ set_sun_azimuth if set_sun_azimuth_sensor == [] else states(set_sun_azimuth_sensor) }}"
  sun_elevation: "{{ set_sun_elevation if set_sun_elevation_sensor == [] else states(set_sun_elevation_sensor) }}"

triggers:
  - trigger: time
    at: !input set_on_time_workday
    id: on_time_workday_trigger

  - trigger: time
    at: !input set_on_time_weekend
    id: on_time_weekend_trigger

  - trigger: time
    at: !input set_off_time
    id: off_time_trigger

  - trigger: sun
    event: sunrise
    id: sunrise_trigger

  - trigger: sun
    event: sunset
    id: sunset_trigger

  - trigger: state
    entity_id: !input forecast_sensor
    id: forecast_trigger

  - trigger: state
    entity_id: !input illuminance_sensor
    id: illuminance_trigger

  - trigger: template
    value_template: "{{ state_attr(sun_sensor,'azimuth') | float > (sun_azimut | int) }}"
    id: sun_azimut_trigger

  - trigger: template
    value_template: "{{ state_attr(sun_sensor,'elevation') | float < (sun_elevation | int) }}"
    id: sun_elevation_trigger

actions:
  - choose:

#########################################################################################################
#
# ВРЕМЯ
#
#########################################################################################################

      - conditions: # Время включения в будни
          - condition: trigger
            id:
              - on_time_workday_trigger
          - condition: template # Будни
            value_template: "{{ workday }}" 
          # - condition: template # Солнце выше горизонта
          #   value_template: "{{ states('sun.sun') == 'above_horizon' }}"
        sequence:
          - action: homeassistant.turn_on
            metadata: {}
            target:
              entity_id: !input phytolamp

      - conditions: # Время открытия в выходные
          - condition: trigger
            id:
              - on_time_weekend_trigger
          - condition: template # Выходные
            value_template: "{{ weekend }}"
          # - condition: template # Солнце выше горизонта
          #   value_template: "{{ states('sun.sun') == 'above_horizon' }}"
        sequence:
          - action: homeassistant.turn_on
            metadata: {}
            target:
              entity_id: !input phytolamp

      - conditions: # Время закрытия
          - condition: trigger
            id:
              - off_time_trigger
          # - condition: template
          #   value_template: "{{ is_close_until_enabled }}"
        sequence:
          - action: homeassistant.turn_on
            metadata: {}
            target:
              entity_id: !input phytolamp


#########################################################################################################
#
# ПОЛОЖЕНИЕ СОЛНЦА
#
#########################################################################################################

      # - conditions: # Включить
      #     - condition: trigger
      #       id:
      #         - sun_elevation_trigger
      #     - condition: template
      #       value_template: "{{ now() <= today_at(set_off_time) }}"
      #   sequence:
      #     - action: homeassistant.turn_on
      #       metadata: {}
      #       target:
      #         entity_id: !input phytolamp

      # - conditions: # Выключить
      #     - condition: trigger
      #       id:
      #         - sun_azimut_trigger
      #     - condition: template
      #       value_template: |
      #         {{ true if not is_forecast_enabled else (states(forecast_sensor) in forecasts) }}
      #     - condition: template
      #       value_template: |
      #         {{ true if not is_illuminance_enabled else states(illuminance_sensor) | int >= set_max_illuminance }}
      #   sequence:
      #     - action: homeassistant.turn_off
      #       metadata: {}
      #       target:
      #         entity_id: !input phytolamp

#########################################################################################################
#
# УПРАВЛЕНИЕ ПО ПОГОДЕ
#
#########################################################################################################


      - conditions: # включить при изменении погоды при включенном режиме положения
          - condition: trigger
            id:
              - forecast_trigger
          - condition: template
            value_template: |
              {{ true if not forecast_sensor == [] else 'extra_forecast' in automation_extra and states(forecast_sensor) in forecasts }}
          - condition: template
            value_template: |
              {{ is_sun_position_enabled and
                (state_attr(sun_sensor,'azimuth') | float(default=45) > sun_azimuth | int
                and state_attr(sun_sensor,'elevation') | float(default=360) > sun_elevation | int) }}
          - condition: template
            value_template: |
              {{ now() >= today_at(on_time) and now() <= today_at(off_time) }}
          - condition: template
            value_template: |
              {{ states(sun_sensor) == 'above_horizon' }}

        sequence:
          - action: homeassistant.turn_off
            metadata: {}
            target:
              entity_id: !input phytolamp

      - conditions: # Выключить при изменении погоды при включенном положения
          - condition: trigger
            id:
              - forecast_trigger
          - condition: template
            value_template: |
              {{ true if not forecast_sensor == [] else 'extra_forecast' in automation_extra and states(forecast_sensor) in forecasts }}
          - condition: template
            value_template: |
              {{ is_sun_position_enabled and
                (state_attr(sun_sensor,'azimuth') | float(default=45) > sun_azimuth | int
                and state_attr(sun_sensor,'elevation') | float(default=360) > sun_elevation | int) }}
          - condition: template
            value_template: |
              {{ now() >= today_at(on_time) and now() <= today_at(off_time) }}
          - condition: template
            value_template: |
              {{ states(sun_sensor) == 'above_horizon' }}
        sequence:
          - action: homeassistant.turn_on
            metadata: {}
            target:
              entity_id: !input phytolamp

#########################################################################################################
#
# УПРАВЛЕНИЕ ПО ОСВЕЩЕННОСТИ
#
#########################################################################################################

      - conditions: # Управлять при изменении уровня освещенности при включенном режиме положения
          - condition: trigger
            id:
              - illuminance_trigger
          - condition: template
            value_template: |
              {{ illuminance_sensor != [] and (set_min_illuminance != 0 or set_max_illuminance != 0) and 'extra_illuminance' in automation_extra }}
          - condition: template
            value_template: |
              {{ this.attributes.last_triggered is none or (now() - this.attributes.last_triggered).total_seconds() > set_illuminance_delay | int }}             
          - condition: template
            value_template: |
              {{ true if not is_sun_position_enabled 
                else (state_attr(sun_sensor,'azimuth') | float(default=45) > (sun_azimuth | int) 
                and state_attr(sun_sensor,'elevation') | float(default=360) > (sun_elevation | int)) }}
          - condition: template
            value_template: |
              {{ now() >= today_at(on_time) and now() <= today_at(off_time) }}
          - condition: template
            value_template: |
              {{ states(sun_sensor) == 'above_horizon' }}
        sequence:
          - choose:
              - conditions: 
                  - condition: template
                    value_template: |
                      {{ states(illuminance_sensor) | int >= set_max_illuminance }}
                sequence:
                  - action: homeassistant.turn_on
                    metadata: {}
                    target:
                      entity_id: !input phytolamp

              - conditions: 
                  - condition: template
                    value_template: |
                      {{ states(illuminance_sensor) | int <= set_min_illuminance }}
                sequence:
                  - action: homeassistant.turn_off
                    metadata: {}
                    target:
                      entity_id: !input phytolamp
