blueprint:
  name: Управление поливом теплицы
  description: |
    ### Управление поливом теплицы.
    <small>Версия 2026.05.01 Сборка 1</small> 

    <small><a href="https://github.com/S0ft0r/ha-blueprints/blob/main/as-is.md">Отказ от ответственности</a></small>
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/greenhouse/dev/dev.greenhouse.yaml
  author: Softor

  input:
    watering_switch:
      name: Реле полива
      description: ""
      selector:
        entity:
          filter:
            - domain:
                - switch
          reorder: false
          multiple: false
    pump_off_auto:
      name: Таймер автоматического отключения
      description: ""
      selector:
        entity:
          filter:
            - domain:
                - timer
          reorder: false
          multiple: false

    morning_section:
      name: Настройки системы для работы утром
      description: |
        Устанавливается время включения, режим работы системы орошения.
      icon: mdi:clock-time-four-outline
      input:
        set_on_time_morning:
          name: Включить утром в
          default: "08:00:00"
          selector:
            time: {}
        set_time_work_morning:
          name: Включать на
          description: Время, на которе включается система орошения 
          default: "00:10:00"
          selector:
            time: {}
        set_on_time_evening:
          name: Включить утром в
          default: "20:00:00"
          selector:
            time: {}
        set_time_work_evening:
          name: Включать на
          description: Время, на которое включается система орошения 
          default: "00:10:00"
          selector:
            time: {}
        waterpump_switch:
          name: Реле насоса
          description: ""
          selector:
            entity:
              filter:
                - domain:
                    - switch
              reorder: false
              multiple: false
        set_time_waterpump_work:
          name: Включать насос на
          description: Время, на которое включается насос перед и после полива 
          default: "00:01:00"
          selector:
            time: {}
        watervalve_switch:
          name: Клапан потока
          description: ""
          default: []
          selector:
            entity:
              filter:
                - domain:
                    - switch
              reorder: false
              multiple: false
        pump_morning_enable:
          name: Включение с утра
          default: false
          selector:
            boolean: {}
        pump_evening_enable:
          name: Включение вечером
          default: false
          selector:
            boolean: {}

trigger_variables:
  watering_switch: !input watering_switch
  watervalve_switch: !input watering_switch
  waterpump_switch: !input watering_switch
  pump_off_auto: !input pump_off_auto

  pump_morning_enable: !input pump_morning_enable 
  pump_evening_enable: !input pump_evening_enable 

  set_time_work_morning: !input set_time_work_morning
  set_time_work_evening: !input set_time_work_evening
  set_time_waterpump_work: !input set_time_waterpump_work

variables:
  time_work_morning: "{{ set_time_work_morning }}"
  time_work_evening: "{{ set_time_work_evening }}"

triggers:
  - at: !input set_on_time_morning
    trigger: time
    id: on_morning_trigger
    enabled: !input pump_morning_enable

  - at: !input set_on_time_evening
    trigger: time
    id: on_evening_trigger
    enabled: !input pump_evening_enable

  - entity_id: !input pump_off_auto
    from: active
    to: idle
    trigger: state
    id: pump_off_auto_trigger

  - entity_id: !input watering_switch
    from: "on"
    to: "off"
    trigger: state
    id: watering_off_trigger

  - entity_id: !input watering_switch
    from: "off"
    to: "on"
    trigger: state
    id: watering_on_trigger

conditions:
  - condition: and
    conditions:
      - condition: template
        value_template: >
          {{ states('input_boolean.summer_pump_mode')=='on' or trigger.id ==
          'pump_off_auto_trigger' or trigger.id == 'watering_off_trigger' }}
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - on_morning_trigger
        sequence:
          - if:
              - condition: state
                entity_id: !input waterpump_switch
                state: "off"
            then:
              - action: switch.turn_on
                target:
                  entity_id: !input waterpump_switch
              - delay: !input set_time_waterpump_work
          - target:
              entity_id: !input watering_switch
            data: {}
            action: switch.turn_on
          - delay: !input set_time_work_morning
          - if:
              - condition: template
                value_template: "{{ watervalve_switch != [] and states(watervalve_switch) not in ['unknown', 'unavailable'] }}"
            then:
              - action: switch.turn_on
                target:
                  entity_id: !input watervalve_switch
              - delay: !input set_time_work_morning
          - data: {}
            target:
              entity_id: !input watering_switch
            action: switch.turn_off
          - data: {}
            target:
              entity_id: !input watervalve_switch
            action: switch.turn_off
          - if:
              - condition: numeric_state
                entity_id: zone.home
                below: 1
            then:
              - delay: !input set_time_waterpump_work
              - target:
                  entity_id: !input waterpump_switch
                data: {}
                action: switch.turn_off

      - conditions:
          - condition: trigger
            id:
              - on_evening_trigger
          - condition: state
            entity_id: input_boolean.pump_evening_enable
            state: "on"
        sequence:
          - if:
              - condition: numeric_state
                entity_id: zone.home
                below: 1
              - confition: state
                entity_id: !input waterpump_switch
                state: "off"
            then:
              - target:
                  entity_id: !input waterpump_switch
                data: {}
                action: switch.turn_on
              - delay: !input set_time_waterpump_work
          - target:
              entity_id: !input watering_switch
            data: {}
            action: switch.turn_on
          # - metadata: {}
          #   data:
          #     duration: "{{ time_work_evening }}"
          #   target:
          #     entity_id:
          #       - timer.pump_off
          #       - timer.w_can_countdown
          #   action: timer.start
          - data: {}
            target:
              entity_id: !input watering_switch
            action: switch.turn_on
          # - wait_for_trigger:
          #     - entity_id:
          #         - timer.pump_off
          #       from: active
          #       to: idle
          #       trigger: state
          #   continue_on_timeout: false
          - delay: !input set_time_work_evening
          - if:
              - condition: template
                value_template: "{{ watervalve_switch != [] and states(watervalve_switch) not in ['unknown', 'unavailable'] }}"
            then:
              - action: switch.turn_on
                target:
                  entity_id: !input watervalve_switch
              - delay: !input set_time_work_evening
          - data: {}
            target:
              entity_id: !input watering_switch
            action: switch.turn_off
          - if:
              - condition: numeric_state
                entity_id: zone.home
                below: 1
            then:
              - delay: !input set_time_waterpump_work
              - target:
                  entity_id: !input waterpump_switch
                data: {}
                action: switch.turn_off

      - conditions:
          - condition: trigger
            id:
              - pump_off_auto_trigger
        sequence:
          - action: switch.turn_off
            target:
              entity_id: !input watering_switch
            data: {}
          - if:
              - condition: numeric_state
                entity_id: zone.home
                below: 1
            then:
              - delay: !input set_time_waterpump_work
              - action: switch.turn_off
                target:
                  entity_id: !input watering_switch
                data: {}

      - conditions:
          - condition: trigger
            id:
              - watering_off_trigger
        sequence:
          - action: timer.finish
            metadata: {}
            data: {}
            target:
              entity_id: !input pump_off_auto
          # - action: timer.finish
          #   metadata: {}
          #   data: {}
          #   target:
          #     entity_id: timer.w_can_countdown

      - conditions:
          - condition: trigger
            id:
              - watering_on_trigger
        sequence:
          - action: timer.start
            metadata: {}
            data: {}
            target:
              entity_id: !input pump_off_auto

mode: parallel
