blueprint:
  name: Управление поливом теплицы
  description: |
    ### Управление поливом теплицы.
    <small>Версия 2026.05.01 Сборка 1</small> 

    <small><a href="https://github.com/S0ft0r/ha-blueprints/blob/main/as-is.md">Отказ от ответственности</a></small>
  domain: automation
  source_url: https://github.com/S0ft0r/ha-blueprints/blob/main/greenhouse/dev/dev.greenhouse.yaml
  author: Softor

  input:
    watering_switch:
      name: Реле/клапан включения полива
      description: |
        Реле/клапан включения полива
        <small>* Поддерживается домены switch и valve</small>
      selector:
        entity:
          filter:
            - domain:
                - switch
                - valve
          reorder: false
          multiple: false
    pump_off_auto:
      name: Таймер автоматического отключения
      description: ""
      selector:
        entity:
          filter:
            - domain:
                - timer
          reorder: false
          multiple: false

    extra_section:
      name: Дополнительные настройки системы
      description: |
        Устанавливается дополнительные настройки.
      icon: mdi:cog
      input:
        waterpump_switch:
          name: Реле насоса
          description: ""
          selector:
            entity:
              filter:
                - domain:
                    - switch
                    - valve
              reorder: false
              multiple: false
        set_time_waterpump_work:
          name: Включать насос на
          description: Время, на которое включается насос перед и после полива 
          default: "00:00:30"
          selector:
            time: {}
        watervalve_switch:
          name: Клапан направления
          description: ""
          default: []
          selector:
            entity:
              filter:
                - domain:
                    - switch
                    - valve
              reorder: false
              multiple: false
        auto_off_pump_time_sensor:
          name: Сенсор количество минут
          default: []
          selector:
            entity:
              filter:
                - domain:
                    - input_number
        set_auto_off_pump_time:
          name: Количество минут
          default: 30
          selector:
            number:
              min: 1
              max: 60
              step: 10
              mode: slider
              unit_of_measurement: "минут"

    morning_section:
      name: Настройки системы для работы утром
      description: |
        Устанавливается время включения, режим работы системы орошения.
      icon: mdi:clock-time-four-outline
      input:
        pump_morning_enable:
          name: Включение с утра
          default: false
          selector:
            boolean: {}
        set_on_time_morning:
          name: Включить утром в
          default: "08:00:00"
          selector:
            time: {}
        set_time_work_morning:
          name: Включать на
          description: Время, на которе включается система орошения 
          default: "00:10:00"
          selector:
            time: {}
        set_working_day_morning:
          name: Режим включения
          default: every_day_morning
          selector:
            select:
              options:
                - label: Ежедневно
                  value: every_day_morning
                - label: Через день
                  value: every_over_day_morning
                - label: Выбор
                  value: select_morning
              mode: dropdown
        set_select_days_morning:
          name: Выбор дней 
          description: Выбор дней
          default: []
          selector:
            select:
              options:
                - label: Понедельник
                  value: day_0_morning
                - label: Вторник
                  value: day_1_morning
                - label: Среда
                  value: day_2_morning
                - label: Четверг
                  value: day_3_morning
                - label: Пятница
                  value: day_4_morning
                - label: Суббота
                  value: day_5_morning
                - label: Воскресенье
                  value: day_6_morning
              sort: false
              multiple: true
              custom_value: false
              mode: list

    evening_section:
      name: Настройки системы для работы вечером
      description: |
        Устанавливается время включения, режим работы системы орошения.
      icon: mdi:clock-time-eight-outline
      input:
        pump_evening_enable:
          name: Включение вечером
          default: false
          selector:
            boolean: {}
        set_on_time_evening:
          name: Включить утром в
          default: "20:00:00"
          selector:
            time: {}
        set_time_work_evening:
          name: Включать на
          description: Время, на которое включается система орошения 
          default: "00:10:00"
          selector:
            time: {}
        set_working_day_evening:
          name: Режим включения вечером
          default: every_day_evening
          selector:
            select:
              options:
                - label: Ежедневно
                  value: every_day_evening
                - label: Через день
                  value: every_over_day_evening
                - label: Выбор
                  value: select_evening
              mode: dropdown
        set_select_days_evening:
          name: Выбор дней 
          description: Выбор дней
          default: []
          selector:
            select:
              options:
                - label: Понедельник
                  value: day_0_evening
                - label: Вторник
                  value: day_1_evening
                - label: Среда
                  value: day_2_evening
                - label: Четверг
                  value: day_3_evening
                - label: Пятница
                  value: day_4_evening
                - label: Суббота
                  value: day_5_evening
                - label: Воскресенье
                  value: day_6_evening
              sort: false
              multiple: true
              custom_value: false
              mode: list

trigger_variables:
  watering_switch: !input watering_switch
  watervalve_switch: !input watervalve_switch
  waterpump_switch: !input watering_switch
  pump_off_auto: !input pump_off_auto

  pump_morning_enable: !input pump_morning_enable 
  pump_evening_enable: !input pump_evening_enable 

  set_time_work_morning: !input set_time_work_morning
  set_time_work_evening: !input set_time_work_evening
  set_time_waterpump_work: !input set_time_waterpump_work

  set_working_day_morning: !input set_working_day_morning
  set_working_day_evening: !input set_working_day_evening
  set_select_days_morning: !input set_select_days_morning
  set_select_days_evening: !input set_select_days_evening

  auto_off_pump_time_sensor: !input auto_off_pump_time_sensor
  set_auto_off_pump_time: !input set_auto_off_pump_time

variables:
  time_work_morning: "{{ set_time_work_morning }}"
  time_work_evening: "{{ set_time_work_evening }}"
  time_waterpump_work: "{{ set_time_waterpump_work }}"

  selected_days_morning: |
    {% set ns = namespace(items=[]) %}
    {% for item in set_select_days_morning %}
      {% set ns.items = ns.items + [item.split('_')[1]|int] %}
    {% endfor %}
    {{ now().weekday() in ns.items }}

  selected_days_evening: |
    {% set ns = namespace(items=[]) %}
    {% for item in set_select_days_evening %}
      {% set ns.items = ns.items + [item.split('_')[1]|int] %}
    {% endfor %}
    {{ now().weekday() in ns.items }}

  auto_off_pump_time: "{{ (set_auto_off_pump_time | int * 60) if auto_off_pump_time_sensor == [] else (states(auto_off_pump_time_sensor)  | int * 60)}}"
  
  watervalve_switch_on: "{{ 'valve.open_valve' if watervalve_switch.split('.')[0] == 'valve' else 'switch.turn_on' }}"
  watervalve_switch_off: "{{ 'valve.close_valve' if watervalve_switch.split('.')[0] == 'valve' else 'switch.turn_off' }}"
  watervalve_switch_toggle: "{{ watervalve_switch.split('.')[0] ~ '.toggle' }}"

  waterpump_switch_on: "{{ 'valve.open_valve' if waterpump_switch.split('.')[0] == 'valve' else 'switch.turn_on' }}"
  waterpump_switch_off: "{{ 'valve.close_valve' if waterpump_switch.split('.')[0] == 'valve' else 'switch.turn_off' }}"
  waterpump_switch_toggle: "{{ waterpump_switch.split('.')[0] ~ '.toggle' }}"

  watering_switch_on: "{{ 'valve.open_valve' if watering_switch.split('.')[0] == 'valve' else 'switch.turn_on' }}"
  watering_switch_off: "{{ 'valve.close_valve' if watering_switch.split('.')[0] == 'valve' else 'switch.turn_off' }}"
  watering_switch_toggle: "{{ watering_switch.split('.')[0] ~ '.toggle' }}"

  watering_state_on: "{{ 'open' if watering_switch.split('.')[0] == 'valve' else 'on' }}"
  watering_state_off: "{{ 'closed' if watering_switch.split('.')[0] == 'valve' else 'off' }}"

triggers:
  - at: !input set_on_time_morning
    trigger: time
    id: on_morning_trigger
    enabled: !input pump_morning_enable

  - at: !input set_on_time_evening
    trigger: time
    id: on_evening_trigger
    enabled: !input pump_evening_enable

  - entity_id: !input pump_off_auto
    from: active
    to: idle
    trigger: state
    id: pump_off_auto_trigger

  - entity_id: !input watering_switch
    trigger: state
    id: watering_toggle_trigger

  - trigger: template
    value_template: "{{ states('sensor.time') == as_timestamp(today_at(time_work_morning) - time_waterpump_work | as_timedelta) | timestamp_custom('%H:%M') }}"
    
    id: time_waterpump_work_trigger

# conditions:
#   - condition: and
#     conditions:
#       - condition: template
#         value_template: >
#           {{ states('input_boolean.summer_pump_mode')=='on' or trigger.id == 'pump_off_auto_trigger' or trigger.id == 'watering_off_trigger' }}

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: 
              - time_waterpump_work_trigger
        sequence:
          - target:
              entity_id: !input waterpump_switch
            data: {}
            action: "{{ waterpump_switch_off }}"

          - condition: trigger
            id:
              - on_morning_trigger
          - condition: template
            value_template: |
              {{ true if ('every_over_day_morning' not in set_working_day_morning) else ((now().timestamp() / 86400) | int % 2 == 0) }}
          - condition: template
            value_template: |
              {{ true if ('select_morning' not in set_working_day_morning) else selected_days_morning }}
        sequence:
          - if:
              - condition: state
                entity_id: !input waterpump_switch
                state: "off"
            then:
              - action: "{{ waterpump_switch_on }}" #           Насос включить
                target:
                  entity_id: !input waterpump_switch
              - delay: !input set_time_waterpump_work #         Задержка перед включением клапана

          - action: "{{ watering_switch_on }}" #            Клапан на воду включен
            target: 
              entity_id: !input watering_switch
            data: {}
          - delay: !input set_time_work_morning #           Задержка для работы
          - if: #                                           Проверка на доступность клапана потока
              - condition: template
                value_template: "{{ watervalve_switch != [] and states(watervalve_switch) not in ['unknown', 'unavailable'] }}"
            then:
              # - action: switch.toggle
              - action: "{{ watervalve_switch_toggle }}" #  Включение клапана потока
                target:
                  entity_id: !input watervalve_switch
              - delay: !input set_time_work_evening #       Задержка для работы
              - action: "{{ watervalve_switch_toggle }}" #  Выключение клапана потока
                target:
                  entity_id: !input watervalve_switch
          - data: {} #                                      Клапан на воду выключен
            target:
              entity_id: !input watering_switch
            action: "{{ watering_switch_off }}"

      - conditions:
          - condition: trigger
            id:
              - on_evening_trigger
          - condition: template
            value_template: |
              {{ true if ('every_over_day_evening' not in set_working_day_evening) else ((now().timestamp() / 86400) | int % 2 == 0) }}
          - condition: template
            value_template: |
              {{ true if ('select_evening' not in set_working_day_evening) else selected_days_evening }}
        sequence:
          - if:
              - condition: state
                entity_id: !input waterpump_switch
                state: "off"
            then:
              - target:
                  entity_id: !input waterpump_switch
                data: {}
                action: "{{ waterpump_switch_on }}"
              - delay: !input set_time_waterpump_work
          - target:
              entity_id: !input watering_switch
            data: {}
            action: "{{ watering_switch_on }}"
          - delay: !input set_time_work_evening
          - if:
              - condition: template
                value_template: "{{ watervalve_switch != [] and states(watervalve_switch) not in ['unknown', 'unavailable'] }}"
            then:
              - action: "{{ watervalve_switch_toggle }}"
                target:
                  entity_id: !input watervalve_switch
              - delay: !input set_time_work_evening
              - action: "{{ watervalve_switch_toggle }}"
                target:
                  entity_id: !input watervalve_switch
          - data: {}
            target:
              entity_id: !input watering_switch
            action: "{{ watering_switch_off }}"

      - conditions:
          - condition: trigger
            id:
              - pump_off_auto_trigger
        sequence:
          - action: "{{ watering_switch_off }}"
            target:
              entity_id: !input watering_switch
            data: {}
          - if:
              - condition: numeric_state
                entity_id: zone.home
                below: 1
            then:
              - delay: !input set_time_waterpump_work
              - action: "{{ waterpump_switch_off }}"
                target:
                  entity_id: !input waterpump_switch
                data: {}

      - conditions:
          - condition: trigger
            id:
              - watering_toggle_trigger
          - condition: template
            value_template: |
              {{ trigger.from_state.state == watering_state_on and trigger.to_state.state == watering_state_off }}
        sequence:
          - action: timer.finish
            metadata: {}
            data: {}
            target:
              entity_id: !input pump_off_auto

      - conditions:
          - condition: trigger
            id:
              - watering_toggle_trigger
          - condition: template
            value_template: |
              {{ trigger.from_state.state == watering_state_off and trigger.to_state.state == watering_state_on }}
        sequence:
          - action: timer.start
            metadata: {}
            data: 
              duration: "{{ auto_off_pump_time }}"
            target:
              entity_id: !input pump_off_auto

mode: parallel
max: 10