name: Проверка Blueprints (Home Assistant)
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'loggia/**.yaml' # ИСПРАВЛЕНО: GitHub Actions проверяет пути относительно корня репозитория
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'loggia/**.yaml' # ИСПРАВЛЕНО
jobs:
  yamllint:
    name: Проверка синтаксиса YAML
    runs-on: ubuntu-latest
    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v4

      - name: Запуск yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: loggia/dev/**.yaml
          config_data: |
            extends: default
            rules:
              line-length: disable
              document-start: disable
              truthy: disable
              trailing-spaces: disable
              new-line-at-end-of-file: 
                level: warning
              braces: disable
              brackets: disable
              comments: disable
              comments-indentation: disable
  ha-validation:
    name: Проверка Home Assistant
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v4
      - name: Подготовка тестовой среды HA # ИСПРАВЛЕНО: Убран лишний префикс папки, теперь файлы реально копируются в песочницу для тестов
        run: |
          mkdir -p fake_config/blueprints/automation/test
          find loggia/ -type f -name "*.yaml" -exec cp {} fake_config/blueprints/automation/test/ \; 
          echo "default_config:" > fake_config/configuration.yaml
      - name: Проверка конфигурации через HA CLI
        uses: frenck/action-home-assistant@v1
        continue-on-error: false # Шаг жестко упадет, если в коде будет хоть одна ошибка
        with:
          path: "fake_config"
          version: "stable" # Берем свежий стабильный релиз ядра для проверки